name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Windows x64
      run: dotnet publish ./src/RCOBOT/RCOBOT.csproj -c Release -r win10-x64 --self-contained true -p:PublishTrimmed=True -p:PublishSingleFile=True
    - name: Publish Linux x64
      run: dotnet publish ./src/RCOBOT/RCOBOT.csproj -c Release -r linux-x64 --self-contained true -p:PublishTrimmed=True -p:PublishSingleFile=True
    - name: Publish OSX x64
      run: dotnet publish ./src/RCOBOT/RCOBOT.csproj -c Release -r osx-x64 --self-contained true -p:PublishTrimmed=True -p:PublishSingleFile=True

    - uses: actions/upload-artifact@v2.2.4
      with:
        name: rcobot-release-win32-selfcontained
        path: ./src/RCOBOT/bin/Release/net5.0/win10-x64
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: rcobot-release-linux64-selfcontained
        path: ./src/RCOBOT/bin/Release/net5.0/linux-x64
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: rcobot-release-osx64-selfcontained
        path: ./src/RCOBOT/bin/Release/net5.0/osx-x64


